version: '3'

silent: true

tasks:

  build:
    desc: Builds the library in debug mode
    cmds:
      - cmd: cargo build

  bench:
    desc: Runs benchmarks
    cmds:
      - cmd: cargo bench -q | grep 'test bench_'

  cov:
    desc: Generates code coverage report
    cmds:
      - cmd: cargo llvm-cov --no-cfg-coverage --no-cfg-coverage-nightly --workspace --html
      - cmd: echo -e "\n\e[1;32mOpen coverage report\x3A\e[0m file:///$(pwd)/target/llvm-cov/html/index.html\n"

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  doc-open:
    desc: Generates and opens the documentation in browser
    cmds:
      - cmd: cargo doc --no-deps --open

  doc:
    desc: Generates the documentation
    cmds:
      - cmd: cargo doc --no-deps

  release:
    desc: Builds the library in release mode
    cmds:
      - cmd: cargo clean
      - cmd: cargo +stable build --release

  test:
    desc: Tests the library in debug mode
    cmds:
      - cmd: cargo test

  clippy:
    desc: Runs linter for all targets
    cmds:
      - cmd: cargo clippy
      - cmd: cargo +nightly clippy --all-targets

  fmt:
    desc: Runs the code formatter
    cmds:
      - cmd: cargo +nightly fmt

  targets:
    desc: Builds release version for multiple targets
    cmds:
      - cmd: cargo +stable build --release --target=x86_64-unknown-linux-gnu
      - cmd: cargo +stable build --release --target=x86_64-unknown-linux-musl
